name: Node

on:
  push:
    branches: [ "main" ]

jobs:
  remote-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fix key permissions
        run: chmod 600 keys/jen_aws.pem

      - name: Run commands on server
        run: |
          ssh -o StrictHostKeyChecking=no -i keys/jen_aws.pem ubuntu@54.167.75.247 << EOF
            cd /home/ubuntu/demorepo/ || exit 1
            touch new_file.txt
            npm install
            nohup npm run start -- -p 3002 > remlfota.log 2>&1 </dev/null &
            disown
          EOF
