name: Deploy-to-EC2

on:
  push:
    branches: [ "main" ]

jobs:
  remote-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (to get the PEM file from repo)
        uses: actions/checkout@v3

      - name: Fix key permissions
        run: chmod 600 keys/jen_aws.pem

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i keys/jen_aws.pem ubuntu@54.167.75.247 << 'EOF'
            cd /home/ubuntu

            # Clone if not already present
            if [ ! -d "my_node_app" ]; then
              git clone https://github.com/MohdFaisalAliKhan/my_node_app.git
            fi

            cd my_node_app
            export PATH=$HOME/.nvm/versions/node/v16.20.2/bin:$PATH
            # Debug path
            pwd
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/npm -v

            # Install dependencies
            /home/ubuntu/.nvm/versions/node/v16.20.2/bin/npm install

            # Start app with nohup
            nohup /home/ubuntu/.nvm/versions/node/v16.20.2/bin/npm run start -- -p 3002 > remlfota.log 2>&1 </dev/null &
            disown
          EOF
