name: Deploy-to-EC2

on:
  push:
    branches: [ "main" ]

jobs:
  remote-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (to get the PEM file from repo)
        uses: actions/checkout@v3

      - name: Fix key permissions
        run: chmod 600 keys/jen_aws.pem

      - name: SSH into server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i keys/jen_aws.pem ubuntu@54.167.75.247 << 'EOF'
            cd /home/ubuntu
            git clone https://github.com/MohdFaisalAliKhan/my_node_app.git
            #curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
            #export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            #[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use # This loads nvm, without auto-using the default version
            cd my_node_app
            pwd
            npm -v
            npm install
            nohup npm run start -- -p 3002 > remlfota.log 2>&1 </dev/null &
            disown
          EOF
